//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predial10.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int linea_inicial_de_detalle_de_recibo {
            get {
                return ((int)(this["linea_inicial_de_detalle_de_recibo"]));
            }
            set {
                this["linea_inicial_de_detalle_de_recibo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int avance_de_linea_detalle_recibo {
            get {
                return ((int)(this["avance_de_linea_detalle_recibo"]));
            }
            set {
                this["avance_de_linea_detalle_recibo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int columna_de_importe {
            get {
                return ((int)(this["columna_de_importe"]));
            }
            set {
                this["columna_de_importe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft sans serif")]
        public string letra_detalle_recibo {
            get {
                return ((string)(this["letra_detalle_recibo"]));
            }
            set {
                this["letra_detalle_recibo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.75")]
        public float tamano_letra_detalle_recibo {
            get {
                return ((float)(this["tamano_letra_detalle_recibo"]));
            }
            set {
                this["tamano_letra_detalle_recibo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int columna_de_concepto {
            get {
                return ((int)(this["columna_de_concepto"]));
            }
            set {
                this["columna_de_concepto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("si")]
        public string grabarencobroexpress {
            get {
                return ((string)(this["grabarencobroexpress"]));
            }
            set {
                this["grabarencobroexpress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SI")]
        public string timbrarprueba {
            get {
                return ((string)(this["timbrarprueba"]));
            }
            set {
                this["timbrarprueba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public string Rezago_urbano {
            get {
                return ((string)(this["Rezago_urbano"]));
            }
            set {
                this["Rezago_urbano"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("361")]
        public string Rezago_rustico {
            get {
                return ((string)(this["Rezago_rustico"]));
            }
            set {
                this["Rezago_rustico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("362")]
        public string Rezago_ejidal {
            get {
                return ((string)(this["Rezago_ejidal"]));
            }
            set {
                this["Rezago_ejidal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("349")]
        public string Recargos {
            get {
                return ((string)(this["Recargos"]));
            }
            set {
                this["Recargos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("303")]
        public string Traslado {
            get {
                return ((string)(this["Traslado"]));
            }
            set {
                this["Traslado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("363")]
        public string Recargosanteriores {
            get {
                return ((string)(this["Recargosanteriores"]));
            }
            set {
                this["Recargosanteriores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("603")]
        public string Regimenfiscal {
            get {
                return ((string)(this["Regimenfiscal"]));
            }
            set {
                this["Regimenfiscal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MCH850101BW8")]
        public string usuariomultifacturas {
            get {
                return ((string)(this["usuariomultifacturas"]));
            }
            set {
                this["usuariomultifacturas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Predial@2018")]
        public string passmultifacturas {
            get {
                return ((string)(this["passmultifacturas"]));
            }
            set {
                this["passmultifacturas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\SDK2\\\\certificados\\\\CUAUTEPECBUENO.cer")]
        public string CertificadoCSD {
            get {
                return ((string)(this["CertificadoCSD"]));
            }
            set {
                this["CertificadoCSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\SDK2\\\\certificados\\\\CUAUTEPECBUENO.key")]
        public string keyCSD {
            get {
                return ((string)(this["keyCSD"]));
            }
            set {
                this["keyCSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MDCH2021")]
        public string passCSD {
            get {
                return ((string)(this["passCSD"]));
            }
            set {
                this["passCSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Morena")]
        public string colorfactura {
            get {
                return ((string)(this["colorfactura"]));
            }
            set {
                this["colorfactura"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pac1.multifacturas.com/cancelacion2022/index.php")]
        public string Predial_10_WSCancelar_v4_Cancelar_cfdi_4_0_SAT {
            get {
                return ((string)(this["Predial_10_WSCancelar_v4_Cancelar_cfdi_4_0_SAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=127.0.0.1;Port=3307;Database=predialchico;User Id=root;Password=root; SslM" +
            "ode=none")]
        public string predialchicoConnectionString {
            get {
                return ((string)(this["predialchicoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("dsn=predial")]
        public string predialString {
            get {
                return ((string)(this["predialString"]));
            }
        }
    }
}
