//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Predial10.WSCancelar_v4 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Cancelar cfdi 4.0 SATBinding", Namespace="urn:wservicewsdl")]
    public partial class Cancelarcfdi40SAT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cancelarCfdiOperationCompleted;
        
        private System.Threading.SendOrPostCallback aceptarCancelarCfdiOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechazarCancelarCfdiOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarCancelarCfdiOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarCfdiRelacionadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Cancelarcfdi40SAT() {
            this.Url = global::Predial10.Properties.Settings.Default.Predial_10_WSCancelar_v4_Cancelar_cfdi_4_0_SAT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cancelarCfdiCompletedEventHandler cancelarCfdiCompleted;
        
        /// <remarks/>
        public event aceptarCancelarCfdiCompletedEventHandler aceptarCancelarCfdiCompleted;
        
        /// <remarks/>
        public event rechazarCancelarCfdiCompletedEventHandler rechazarCancelarCfdiCompleted;
        
        /// <remarks/>
        public event consultarCancelarCfdiCompletedEventHandler consultarCancelarCfdiCompleted;
        
        /// <remarks/>
        public event consultarCfdiRelacionadoCompletedEventHandler consultarCfdiRelacionadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#cancelarCfdi", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public respuesta cancelarCfdi(datos datos) {
            object[] results = this.Invoke("cancelarCfdi", new object[] {
                        datos});
            return ((respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarCfdiAsync(datos datos) {
            this.cancelarCfdiAsync(datos, null);
        }
        
        /// <remarks/>
        public void cancelarCfdiAsync(datos datos, object userState) {
            if ((this.cancelarCfdiOperationCompleted == null)) {
                this.cancelarCfdiOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarCfdiOperationCompleted);
            }
            this.InvokeAsync("cancelarCfdi", new object[] {
                        datos}, this.cancelarCfdiOperationCompleted, userState);
        }
        
        private void OncancelarCfdiOperationCompleted(object arg) {
            if ((this.cancelarCfdiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCfdiCompleted(this, new cancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#aceptarCancelarCfdi", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public respuesta aceptarCancelarCfdi(datos datos) {
            object[] results = this.Invoke("aceptarCancelarCfdi", new object[] {
                        datos});
            return ((respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void aceptarCancelarCfdiAsync(datos datos) {
            this.aceptarCancelarCfdiAsync(datos, null);
        }
        
        /// <remarks/>
        public void aceptarCancelarCfdiAsync(datos datos, object userState) {
            if ((this.aceptarCancelarCfdiOperationCompleted == null)) {
                this.aceptarCancelarCfdiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaceptarCancelarCfdiOperationCompleted);
            }
            this.InvokeAsync("aceptarCancelarCfdi", new object[] {
                        datos}, this.aceptarCancelarCfdiOperationCompleted, userState);
        }
        
        private void OnaceptarCancelarCfdiOperationCompleted(object arg) {
            if ((this.aceptarCancelarCfdiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aceptarCancelarCfdiCompleted(this, new aceptarCancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#rechazarCancelarCfdi", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public respuesta rechazarCancelarCfdi(datos datos) {
            object[] results = this.Invoke("rechazarCancelarCfdi", new object[] {
                        datos});
            return ((respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void rechazarCancelarCfdiAsync(datos datos) {
            this.rechazarCancelarCfdiAsync(datos, null);
        }
        
        /// <remarks/>
        public void rechazarCancelarCfdiAsync(datos datos, object userState) {
            if ((this.rechazarCancelarCfdiOperationCompleted == null)) {
                this.rechazarCancelarCfdiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechazarCancelarCfdiOperationCompleted);
            }
            this.InvokeAsync("rechazarCancelarCfdi", new object[] {
                        datos}, this.rechazarCancelarCfdiOperationCompleted, userState);
        }
        
        private void OnrechazarCancelarCfdiOperationCompleted(object arg) {
            if ((this.rechazarCancelarCfdiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechazarCancelarCfdiCompleted(this, new rechazarCancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#consultarCancelarCfdi", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public respuestaCCancelar consultarCancelarCfdi(datos datos) {
            object[] results = this.Invoke("consultarCancelarCfdi", new object[] {
                        datos});
            return ((respuestaCCancelar)(results[0]));
        }
        
        /// <remarks/>
        public void consultarCancelarCfdiAsync(datos datos) {
            this.consultarCancelarCfdiAsync(datos, null);
        }
        
        /// <remarks/>
        public void consultarCancelarCfdiAsync(datos datos, object userState) {
            if ((this.consultarCancelarCfdiOperationCompleted == null)) {
                this.consultarCancelarCfdiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarCancelarCfdiOperationCompleted);
            }
            this.InvokeAsync("consultarCancelarCfdi", new object[] {
                        datos}, this.consultarCancelarCfdiOperationCompleted, userState);
        }
        
        private void OnconsultarCancelarCfdiOperationCompleted(object arg) {
            if ((this.consultarCancelarCfdiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCancelarCfdiCompleted(this, new consultarCancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#consultarCfdiRelacionado", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public respuesta consultarCfdiRelacionado(datosRelacionados datos) {
            object[] results = this.Invoke("consultarCfdiRelacionado", new object[] {
                        datos});
            return ((respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void consultarCfdiRelacionadoAsync(datosRelacionados datos) {
            this.consultarCfdiRelacionadoAsync(datos, null);
        }
        
        /// <remarks/>
        public void consultarCfdiRelacionadoAsync(datosRelacionados datos, object userState) {
            if ((this.consultarCfdiRelacionadoOperationCompleted == null)) {
                this.consultarCfdiRelacionadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarCfdiRelacionadoOperationCompleted);
            }
            this.InvokeAsync("consultarCfdiRelacionado", new object[] {
                        datos}, this.consultarCfdiRelacionadoOperationCompleted, userState);
        }
        
        private void OnconsultarCfdiRelacionadoOperationCompleted(object arg) {
            if ((this.consultarCfdiRelacionadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCfdiRelacionadoCompleted(this, new consultarCfdiRelacionadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
    public partial class datos {
        
        private string usuarioField;
        
        private string passField;
        
        private string accionField;
        
        private string produccionField;
        
        private string uuidField;
        
        private string rfcField;
        
        private string passwordField;
        
        private string motivoField;
        
        private string folioSustitucionField;
        
        private string b64CerField;
        
        private string b64KeyField;
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
        
        /// <remarks/>
        public string accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
        
        /// <remarks/>
        public string produccion {
            get {
                return this.produccionField;
            }
            set {
                this.produccionField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string folioSustitucion {
            get {
                return this.folioSustitucionField;
            }
            set {
                this.folioSustitucionField = value;
            }
        }
        
        /// <remarks/>
        public string b64Cer {
            get {
                return this.b64CerField;
            }
            set {
                this.b64CerField = value;
            }
        }
        
        /// <remarks/>
        public string b64Key {
            get {
                return this.b64KeyField;
            }
            set {
                this.b64KeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
    public partial class datosRelacionados {
        
        private string usuarioField;
        
        private string passField;
        
        private string accionField;
        
        private string produccionField;
        
        private string uuidField;
        
        private string rfc_receptorField;
        
        private string passwordField;
        
        private string b64Cer_receptorField;
        
        private string b64Key_receptorField;
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
        
        /// <remarks/>
        public string accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
        
        /// <remarks/>
        public string produccion {
            get {
                return this.produccionField;
            }
            set {
                this.produccionField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string rfc_receptor {
            get {
                return this.rfc_receptorField;
            }
            set {
                this.rfc_receptorField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string b64Cer_receptor {
            get {
                return this.b64Cer_receptorField;
            }
            set {
                this.b64Cer_receptorField = value;
            }
        }
        
        /// <remarks/>
        public string b64Key_receptor {
            get {
                return this.b64Key_receptorField;
            }
            set {
                this.b64Key_receptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
    public partial class respuestaCCancelar {
        
        private string codigo_mf_numeroField;
        
        private string codigo_mf_textoField;
        
        private string mensaje_originalField;
        
        private string statusField;
        
        private string json_uuidsField;
        
        private string codigo_respuesta_satField;
        
        private string codigo_respuesta_sat_textoField;
        
        private string codigo_respuesta_sat_texto_descripcionField;
        
        private string produccionField;
        
        private string accionField;
        
        /// <remarks/>
        public string codigo_mf_numero {
            get {
                return this.codigo_mf_numeroField;
            }
            set {
                this.codigo_mf_numeroField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_mf_texto {
            get {
                return this.codigo_mf_textoField;
            }
            set {
                this.codigo_mf_textoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje_original {
            get {
                return this.mensaje_originalField;
            }
            set {
                this.mensaje_originalField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string json_uuids {
            get {
                return this.json_uuidsField;
            }
            set {
                this.json_uuidsField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_respuesta_sat {
            get {
                return this.codigo_respuesta_satField;
            }
            set {
                this.codigo_respuesta_satField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_respuesta_sat_texto {
            get {
                return this.codigo_respuesta_sat_textoField;
            }
            set {
                this.codigo_respuesta_sat_textoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_respuesta_sat_texto_descripcion {
            get {
                return this.codigo_respuesta_sat_texto_descripcionField;
            }
            set {
                this.codigo_respuesta_sat_texto_descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string produccion {
            get {
                return this.produccionField;
            }
            set {
                this.produccionField = value;
            }
        }
        
        /// <remarks/>
        public string accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
    public partial class respuesta {
        
        private string codigo_mf_numeroField;
        
        private string codigo_mf_textoField;
        
        private string mensaje_originalField;
        
        private string acuseField;
        
        private string statusField;
        
        private string uuidField;
        
        private string codigo_respuesta_satField;
        
        private string codigo_respuesta_sat_textoField;
        
        private string codigo_respuesta_sat_texto_descripcionField;
        
        private string produccionField;
        
        private string accionField;
        
        /// <remarks/>
        public string codigo_mf_numero {
            get {
                return this.codigo_mf_numeroField;
            }
            set {
                this.codigo_mf_numeroField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_mf_texto {
            get {
                return this.codigo_mf_textoField;
            }
            set {
                this.codigo_mf_textoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje_original {
            get {
                return this.mensaje_originalField;
            }
            set {
                this.mensaje_originalField = value;
            }
        }
        
        /// <remarks/>
        public string acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_respuesta_sat {
            get {
                return this.codigo_respuesta_satField;
            }
            set {
                this.codigo_respuesta_satField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_respuesta_sat_texto {
            get {
                return this.codigo_respuesta_sat_textoField;
            }
            set {
                this.codigo_respuesta_sat_textoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_respuesta_sat_texto_descripcion {
            get {
                return this.codigo_respuesta_sat_texto_descripcionField;
            }
            set {
                this.codigo_respuesta_sat_texto_descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string produccion {
            get {
                return this.produccionField;
            }
            set {
                this.produccionField = value;
            }
        }
        
        /// <remarks/>
        public string accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cancelarCfdiCompletedEventHandler(object sender, cancelarCfdiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCfdiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCfdiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void aceptarCancelarCfdiCompletedEventHandler(object sender, aceptarCancelarCfdiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aceptarCancelarCfdiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aceptarCancelarCfdiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void rechazarCancelarCfdiCompletedEventHandler(object sender, rechazarCancelarCfdiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechazarCancelarCfdiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechazarCancelarCfdiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void consultarCancelarCfdiCompletedEventHandler(object sender, consultarCancelarCfdiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCancelarCfdiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCancelarCfdiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuestaCCancelar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuestaCCancelar)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void consultarCfdiRelacionadoCompletedEventHandler(object sender, consultarCfdiRelacionadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCfdiRelacionadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCfdiRelacionadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591